create table foo(a,b,c);
insert into foo (a,b,c) values ('1','1','1');
select * from foo where a='1';
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
insert into foo (a,b,c) values ('1','1','1');
get cursor 0;
advance cursor 0;
get cursor 0;
advance cursor 0;
get cursor 0;
advance cursor 0;
